routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('category','CategoryController');
Route::resource('product','ProductController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
	protected $table = 'categories';
protected $fillable = [
'name'
];
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{ 
    protected $table = 'products';
protected $fillable = [
'name',
'status',
'image',
'category_id',
'desc'
];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::get();

        return view('view_category')->with([
'cats' => $categories
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('add_category');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd('store');
        $input = $request->all();
        // $category = Category::create([
        //     'name' => $input['cname'],
        // ]);     
           $category = Category::create($input);
        // dd($input['cname'],$category);
        return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::find($id);

        dd($category);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
return view('add_category')->with([
'cat' => $category,
'edit' => 1,
        ]);;
        dd($category);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd('update');
        $category = Category::find($id);
        $input = $request->all();
        $category->fill(['name'=>$input['cname']])->save();
        return redirect()->route('category.index');
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::get();

        return view('view_product')->with([
'prod' => $products
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::get();
        return view('add_product')->with([
'categories' => $categories
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $product = Product::create($input);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);

        dd($product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
return view('add_product')->with([
'prod' => $product,
'edit' => 1,
        ]);;
        dd($product);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $id)
    {
        $product = Product::find($id);
        $input = $request->all();
        $product->fill(['name'=>$input['cname']])->save();
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        //
    }
}

resources/views/add_category.blade.php
<!DOCTYPE html>
<html>
	<head>
		<title>Add Category</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" crossorigin="anonymous">
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="#">Navbar</a>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Product
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" href="#">Add Product</a>
								<a class="dropdown-item" href="#">View Product</a>
								
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Category
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" href="{{ route('category.create') }}">Add Category</a>
								<a class="dropdown-item" href="{{ route('category.index') }}">View Category</a>
								
							</div>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">
			<div class="row justify-content-md-center" >
				<div class="col-md-4">
					<div class="card" style="
						margin-top: 50px;
						padding: 20px;"
						>
						<div class="card-body">
							<div class="row justify-content-md-center">
								<h3>{{ isset($edit) ? 'Edit' : 'Add'}} Category</h3>
							</div>
							@if (isset($edit))
							<form action="{{ route('category.update',$cat->id) }}" method="POST">
								<input type="hidden" name="_method" value="PUT">
								@else
								<form action="{{ route('category.store') }}" method="POST">
									@endif
									
									<input type="hidden" name="_token" value="{{ csrf_token() }}">
									<div class="row" style="
										margin-bottom: 10px;">
										<input type="text" name="name" id="title" class="form-control" maxlength="50" autocomplet="off" placeholder="Category" required value="{{ isset($edit) ? $cat->name : null}}"></input>
									</div>
									<div class="row">
										<button type="submit" class="btn btn-success btn-block">Submit</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
			<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
			<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
		</body>
	</html>

resources/views/add_product.blade.php
<html>
	<head>
		<title>Add Product</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" crossorigin="anonymous">
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="#">Navbar</a>
				
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Product
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" href="#">Add Product</a>
								<a class="dropdown-item" href="#">View Product</a>
								
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Category
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" href="{{ route('category.create') }}">Add Category</a>
								<a class="dropdown-item" href="{{ route('category.index') }}">View Category</a>
								
							</div>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">
			<div class="row justify-content-md-center" >
				<div class="col-md-8" style="margin-top: 55px;border: 1px solid;">
					<h3 style="padding-top: 11px;">Add Product</h3>
					<hr>
					@if (isset($edit))
							<form action="{{ route('product.update',$prod->id) }}" method="POST">
								<input type="hidden" name="_method" value="PUT">
								@else
					<form method="POST" action="{{ route('product.store') }}">
						@endif
						<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<div class="form-row">
							<div class="col">
								<div class="form-group">
									

									<label  class="mr-sm-4" for="inlineFormCustomSelect">Category Id</label>
									<select name="category_id" class="custom-select mr-sm-4" id="inlineFormCustomSelect" placeholder="Choose" required value="{{ isset($edit) ? $prod->id : null}}">

										{{-- foreach(\App\Category::all() as $c) --}}
										@foreach($prod as $p)
										
										<option value="{{ $p->category_id }}">{{ $p->name }}</option>

									@endforeach
									</select>
								</div>
							</div>
							<div class="col">
								<div class="form-group">
									<label class="mr-sm-4" for="inlineFormCustomSelect">Status</label>
									<select name="status" class="custom-select mr-sm-4" id="inlineFormCustomSelect" required value="{{ isset($edit) ? $prod->status : null}}">
										<!-- <option selected>Choose...</option> -->
										<option value="1">Avalable</option>
										<option selected value="0">Unavalable</option>
									</select>
								</div>
							</div>
						</div>
						<div class="form-row">
							<div class="col">
								<div class="form-group">
									<label for="formGroupExampleInput2">Product Name</label>
									<input name="name" type="text" class="form-control" id="formGroupExampleInput2" placeholder="Product Name" required value="{{ isset($edit) ? $prod->name : null}}">
								</div>
							</div>
							<div class="col">
								<div class="form-group">
									<label for="formGroupExampleInput2">Image</label>
									<input name="image" type="file" class="form-control" id="formGroupExampleInput2" placeholder="Image" required value="{{ isset($edit) ? $prod->image : null}}">
								</div>
							</div>
						</div>
						<div class="form-group">
							<label for="exampleFormControlTextarea1">Description</label>
							<textarea name="desc" class="form-control" id="exampleFormControlTextarea1" rows="3" required value="{{ isset($edit) ? $prod->desk : null}}"></textarea>
						</div>
					
					<div class="form-group">
						<button type="submit" class="btn btn-success btn-block">Submit</button>
					</div>
					</form>
				</div>
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	</body>
</html>

resources/views/view_category.blade.php
<!DOCTYPE html>
<html>
	<head>
		<title>View Categories</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" crossorigin="anonymous">
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="#">Navbar</a>
			</div>
		</nav>
		<div class="container">
			<a href="{{ route('category.create') }}" class="btn btn-primary">Add Category</a>
			<div class="row justify-content-md-center" >
				<div class="col-md-8" style="margin-top: 97px;">
					<table class="table" style="border: 2px solid;">
						<thead>
							<tr>
								<th scope="col">ID</th>
								<th scope="col">Name</th>
								<th scope="col">DATE</th>
								<th scope="col">ACTION</th>
							</tr>
						</thead>
						<tbody>
							@foreach($cats as $c)
							<tr>
								<th scope="row">{{ $c->id }}</th>
								<td>{{ $c->name }}</td>
								<td>{{ $c->created_at->format('d-m-Y') }}</td>
								<td>
									<a href="{{ route('category.show',$c->id) }}" class="btn btn-primary">Show</a>
									<a href="{{ route('category.edit',$c->id) }}" class="btn btn-warning">Edit <i class="fa far far-pencil"></i></a>
								</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</body>
</html>

resources/views/view_product.blade.php
<!DOCTYPE html>
<html>
	<head>
		<title>View Categories</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" crossorigin="anonymous">
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="#">Navbar</a>
			</div>
		</nav>
		<div class="container">
			<a href="#" class="btn btn-primary">Add Product</a>
			<div class="row justify-content-md-center" >
				<div class="col-md-8" style="margin-top: 97px;">
					<table class="table" style="border: 2px solid;">
						<thead>
							<tr>
								<th scope="col">ID</th>
								<th scope="col">Name</th>
								<th scope="col">Image</th>
								<th scope="col">Discription</th>
								<th scope="col">Status</th>
								<th scope="col">Action</th>
							</tr>
						</thead>
						<tbody>
							@foreach($prod as $p)
							<tr>
								<th scope="row">{{$p->category_id}}</th>
								<td>{{$p->name}}</td>
								<td>{{$p->image}}</td>
								<td>{{$p->desc}}</td>
								<td>{{$p->status}}</td>
								<td><a href="{{ route('product.show',$p->id) }}" class="btn btn-primary">Show</a>
									<a href="{{ route('product.edit',$p->id) }}" class="btn btn-warning">Edit</a></td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</body>
</html>